### PR TITLE
Regex matching

### LINKED ISSUE #49: Any way to disable filetypes that match a regex?
It's pretty annoying when comments are getting highlighted. I can disable them for each filetype manually in the vimrc, but it would be better if you allowed regex.

Then we could do something like:
```vim
let g:Illuminate_ftHighlightGroups = {
      \ '*:blacklist': ['.*[cC]omment.*']
      \ }
```

i.e. `*` => For all filetypes
`:blacklist` => blacklist
`'.*[cC]omment.*'` => match any highlight group containing `comment` or `Comment` in it's name

### PR DESCRIPTION
**Pull request by subnut**
Closes #49 

I've also moved the configuration to the plugin directory, since that's where it should actually be.

### CODE REVIEW

**Review by RRethy — COMMENTED** [review]
This is an adhoc solution and has a config variable named `...list...` with a type `String`. If this was merged it would need to be a list, similar to the other config options. That being said, I'm leaning towards a callback, i'll try an implementation tmrw. Docs will also need updating.

**Comment by subnut** [comment]
> That being said, I'm leaning towards a callback, i'll try an implementation tmrw

OK.. Should I close this PR?

**Comment by RRethy** [comment]
> > That being said, I'm leaning towards a callback, i'll try an implementation tmrw
> 
> OK.. Should I close this PR?

Leave open for now.

**Comment by RRethy** [comment]
https://github.com/RRethy/vim-illuminate/commit/b3727c125efe5aace5ae861b85fd9e9df41b01b7

**Pull request closed without merging**
