### PR TITLE
Add autocmds for lua

### PR DESCRIPTION
**Pull request by tamago324**
Thanks for creating and maintaining a great plugin!

Added autocmd as in VimScript.

### CODE REVIEW

**Review by RRethy — COMMENTED** [review]
Can you add a rational to the PR description. Omitting these were intentional, the previous method was limited in adding window highlighting, but the Neovim API adds buffer highlighting so the additional window autocmds were not added. I probably won't merge this.

**Comment by tamago324** [comment]
Thanks for the review.
Sorry. I didn't explain it well enough.

The intention of this PR was to control the highlighting by g:Illuminate_insert_mode_highlight.
Therefore, I was happy to add only InsertEnter and CursorMovedI.
However, in VimScript, WinLeave, BufLeave and InsertLeave also execute autocmd, so I added lua as well.


Also, I tried insertLeave without autocmd, and the highlighting was done when I exited Insert Mode, so I don't think insertLeave is necessary either.

If possible, I would like to remove autocmd for WinLeave, BufLeave and InsertLeave, how about that?


Translated with www.DeepL.com/Translator (free version)

**Comment by RRethy** [comment]
These autocmds open up potential for a lot of race conditions because `vim.lsp.buf.document_highlight()` is an async function. I'll think about adding back `g:Illuminate_insert_mode_highlight` but I'm going to close this PR for now. I'm planning on a partial rewrite of this plugin eventually where I can think about adding back that option.

**Comment by tamago324** [comment]
Thank you for your explanation.

I understand. I'm really looking forward to the option of no highlighting in insert mode when this plugin is rewritten.

Thank you.

**Pull request closed without merging**
