### PR TITLE
feat: jump to word without lsp

### PR DESCRIPTION
**Pull request by Massolari**
Fixes: #88

### CODE REVIEW

**Comment by RRethy** [comment]
This would break the plugin for Vim users. I can take a look at this another time.

**Comment by Massolari** [comment]
Oh, sorry. I didn't realize you want to support Vim.

**Comment by RayZ0rr** [comment]
@Massolari Does your fork support this? Can it be used by nvim only users ?

`use 'Massolari/vim-illuminate'`

**Comment by Massolari** [comment]
@RayZ0rr Yeah! I'm using it everyday and its working fine

**Pull request closed without merging**
